### ISSUE TITLE
Allow different implementations of KyuubiOperation class

### ISSUE THREAD

**Issue by dharm82465** [yaooqinn/kyuubi#120]
**Is your feature request related to a problem? Please describe.**
In the project that I am currently working on, I need an ability to use different implementation of KyuubiOperation instead of the one in KyuubiOperation.scala. 

**Describe the solution you'd like**
I propose creating Scala trait like the one shown below and replacing `KyuubiOperation` -> `IKyuubiOperation` in `KyuubiSession.scala`, `OperationManager.scala` and implementing configurable operation class selection in `OperationManager.newExecuteStatementOperation()`. 

The total change is around 10-20 lines of Scala plus the following trait:

```
trait IKyuubiOperation {
  def getSession: KyuubiSession
  def getHandle: OperationHandle
  def getProtocolVersion: TProtocolVersion
  def getStatus: OperationStatus
  def getOperationLog: OperationLog
  @throws[KyuubiSQLException]
  def run(): Unit
  def close(): Unit
  def cancel(): Unit
  def getResultSetSchema: StructType
  def getNextRowSet(order: FetchOrientation, maxRowsL: Long): RowSet
  def isTimedOut: Boolean
} 
```
I can provide a pull request if needed.

**Comment by yaooqinn** [comment]
@dharm82465 please feel free to make a pr
