### ISSUE TITLE
while i execute insert type sql,i got a Filesystem closed erro

### ISSUE THREAD

**Issue by oOKevinOo** [yaooqinn/kyuubi#137]
while i execute insert type sql,i got a Filesystem closed erro,log fellow:
![image](https://user-images.githubusercontent.com/24331196/50513085-83aae080-0ad0-11e9-940f-e007f1d13d6c.png)
did anyone meet such erro,and set fs.hdfs.impl.disable.cache = true; can fix it!!!

**Comment by yaooqinn** [comment]
It seems related to https://github.com/yaooqinn/kyuubi/blob/master/kyuubi-server/src/main/scala/yaooqinn/kyuubi/session/KyuubiSession.scala#L203

Are you running kyuubi against a non secured/kerberized  cluster?

**Comment by AngersZhuuuu** [comment]
meet same case,  too long , forgot how i have fix it ...
 try this too, work fine but make dfs action slow. set fs.hdfs.impl.disable.cache = true

**Comment by chuangehh** [comment]
Temporary solution：
$ bin/start-kyuubi.sh \ 
    --master yarn \
    --deploy-mode client \
    --driver-memory 10g \
    --conf spark.kyuubi.frontend.bind.port=10009
    **--conf spark.hadoop.fs.hdfs.impl.disable.cache=true**
