### ISSUE TITLE
kyuubi web ui --kyuubi Tab

### ISSUE THREAD

**Issue by logant-ioc** [yaooqinn/kyuubi#138]
**Describe the bug**
如果打开不同用户的webui 在查看用户执行的sql记录时，会调到其他用户的sql记录
**To Reproduce**
1. Configurations
2. Environments
spark2.2
3. Operations
![default](https://user-images.githubusercontent.com/36909514/50537719-95f35000-0b9e-11e9-9847-a4e6f6898149.png)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yaooqinn** [comment]
https://github.com/yaooqinn/kyuubi/issues/72 check this
