### ISSUE TITLE
while i trying query partited big table,some erro will accur!

### ISSUE THREAD

**Issue by oOKevinOo** [yaooqinn/kyuubi#139]
![image](https://user-images.githubusercontent.com/24331196/50815965-1150c080-135a-11e9-951a-f5bc13a7b16c.png)
erro like bellow,how can i solve it!!!

**Comment by yaooqinn** [comment]
could you please provide more information,  so we can reproduce it

**Comment by oOKevinOo** [comment]
i seems the spark version bug.i search lots of page,it was fixed for higher spark version.
now i query data without full table scan will be run normally!

**Comment by yaooqinn** [comment]
so glad that you fixed it on your own
