### ISSUE TITLE
Cannot get tables metadata

### ISSUE THREAD

**Issue by benmizrahi** [yaooqinn/kyuubi#156]
Describe the bug:
Trying to connect to Kyuubi via JDBC connection (with client such as Dbeaver) and I cannot see tables list tree in the UI.
The client throws method not implemented exception.

To Reproduce Steps to reproduce the behavior:

1. Run Kyuubi on yarn client in client mode
2. Make sure your yarn metastore configuration denfined to existing hive metastore.
3. Open dbeaver client and connect via hive2 driver to the running Kyuubi instance.
4. Open tables tab in the client and it throws exception: method not implemented

Expected behavior: show tables list based on the schema in the connection string.

Thanks a lot for helping:)

**Comment by yaooqinn** [comment]
thanks @benmizrahi to point this out, we haven't implement any METASTORE operations yet. And I think we should have it fixed ASAP.

**Comment by benmizrahi** [comment]
Do you have any time estimation for development?

**Comment by yaooqinn** [comment]
I am glad that you can help with this

**Comment by wonb168** [comment]
is v0.7 released?

**Comment by yaooqinn** [comment]
not yet
