### ISSUE TITLE
kyuubi-cluster: implement sparkSession management for different kyuubiAppMaster mode

### ISSUE THREAD

**Issue by turboFei** [yaooqinn/kyuubi#176]
**Is your feature request related to a problem? Please describe.**
For the kyuubiAppMaster, it should have two modes: specific mode for a user and  normal mode for all user.
For the normal mode, it receive all requests from all users and it would be alive until be killed.
Therefor, its session management has no difference with local kyuubiServer.

For the specific mode, it only receive the requests from a specific user, and it should unregister itself when it has idled for a define timeout.

**Describe the solution you'd like**
There should be a parameter present the mode of kyuubiAppMaster.
```
spark.kyuubi.yarn.appmaster.specific.mode    
```
For the specific mode,  we would implement SpecifiCSparkSessionCacheMgr extends sparkSessionCacheMgr which only has one active sparkContext and the sparkSession cleaner thread should stop the kyuubiAppMaster when sparkContext idle for more than defined duration.

**Comment by AngersZhuuuu** [comment]
you can change code to match your use case , In multi-sparkcontext in one jvm, one spark context stooped, it will clear the value in SparkContext.activeContext. Other SparkContext 's job will failed, In our case, we don't close sparkcontext with timeout config
