### ISSUE TITLE
use dbeaver connet to kyuubi error

### ISSUE THREAD

**Issue by wonb168** [yaooqinn/kyuubi#185]
can not show tables in dbeaver, 

SQL 错误: Method Not Implemented!
  Method Not Implemented!
  Method Not Implemented!
    yaooqinn.kyuubi.KyuubiSQLException:Method Not Implemented!
    yaooqinn.kyuubi.KyuubiSQLException:Method Not Implemented!

**Comment by yaooqinn** [comment]
#156

**Comment by wonb168** [comment]
when v0.7 release?
