### ISSUE TITLE
Error: Starting Kyuubi by client yaooqinn.kyuubi.service.ServiceException: Unable to create Kyuubi namespace /kyuubiserver on ZooKeeper

### ISSUE THREAD

**Issue by FuShuaiWang** [yaooqinn/kyuubi#210]
**Describe the bug**
when i start Kyuubi High Availability ,the log has a error:
Error: Starting Kyuubi by client yaooqinn.kyuubi.service.ServiceException: Unable to create Kyuubi namespace /kyuubiserver on ZooKeeper

**To Reproduce**
1. Configurations
frist i export environment:
export HADOOP_CONF_DIR=/etc/hadoop/conf
export SPARK_HOME=/opt/spark/spark-2.1.3-bin-hadoop2.6
second i editor spark-deaults.conf file to add these:
spark.yarn.keytab=/opt/spark/hive.keytab

2. Environments
spark:spark-2.1.3-bin-hadoop2.6
linux:redhat6.5
java:1.8
kyuubi:kyuubi-0.7.0-bin-spark-2.1.3
hadoop: CDH-5.13.3 
zookeeper:3.4.5+cdh5.13.3

3. Operations
/opt/spark/kyuubi-0.7.0-bin-spark-2.1.3/bin/start-kyuubi.sh \
--master yarn \
--conf spark.kyuubi.ha.enabled=true \
--conf spark.kyuubi.ha.zk.quorum=134.64.14.231,134.64.14.232,134.64.14.233 \
--conf spark.kyuubi.ha.zk.client.port=2181 \
--conf spark.kyuubi.authentication=KERBEROS \
--conf spark.driver.memory=20g \
--conf spark.hadoop.fs.hdfs.impl.disable.cache=true \
--conf spark.executor.heartbeatInterval=30s 

19/07/25 14:56:02 INFO state.ConnectionStateManager: State change: CONNECTED
19/07/25 14:56:02 ERROR client.ZooKeeperSaslClient: An error: (java.security.PrivilegedActionException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Server not found in Kerberos database (7) - UNKNOWN_SERVER)]) occurred when evaluating Zookeeper Quorum Member's  received SASL token. This may be caused by Java's being unable to resolve the Zookeeper Quorum Member's hostname correctly. You may want to try to adding '-Dsun.net.spi.nameservice.provider.1=dns,sun' to your client's JVMFLAGS environment. Zookeeper Client will go to AUTH_FAILED state.
19/07/25 14:56:02 ERROR zookeeper.ClientCnxn: SASL authentication with Zookeeper Quorum member failed: javax.security.sasl.SaslException: An error: (java.security.PrivilegedActionException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Server not found in Kerberos database (7) - UNKNOWN_SERVER)]) occurred when evaluating Zookeeper Quorum Member's  received SASL token. This may be caused by Java's being unable to resolve the Zookeeper Quorum Member's hostname correctly. You may want to try to adding '-Dsun.net.spi.nameservice.provider.1=dns,sun' to your client's JVMFLAGS environment. Zookeeper Client will go to AUTH_FAILED state.
19/07/25 14:56:02 ERROR curator.ConnectionState: Authentication failed
Error: Starting Kyuubi by client yaooqinn.kyuubi.service.ServiceException: Unable to create Kyuubi namespace /kyuubiserver on ZooKeeper
Run with --help for usage help or --verbose for debug output
19/07/25 14:56:02 INFO server.KyuubiServer: Shutting down KyuubiServer
19/07/25 14:56:02 INFO util.ShutdownHookManager: Shutdown hook called

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yaooqinn** [comment]
missing principal？

**Comment by FuShuaiWang** [comment]
I just changed the zk host ip to the host name,then it's ok!
I feel incredible.

**Comment by FuShuaiWang** [comment]
thanks for your help

> missing principal？
I just changed the zk host ip to the host name,then it's ok!
I feel incredible.
thanks for your help,i temporarily close this issue.

**Comment by FuShuaiWang** [comment]
> missing principal？

i just change the zk ip to hostname,then it's ok!I haven't understood this reason for the time being.
Thank you for your help.I temporarily close this issue.
