### ISSUE TITLE
Error: Starting Kyuubi by client yaooqinn.kyuubi.service.ServiceException: Unable to create Kyuubi namespace /kyuubiserver on ZooKeeper

### ISSUE THREAD

**Issue by SunFlowerY1** [yaooqinn/kyuubi#215]
**Describe the bug**
when i set the keytab and principal in the spark-defaults-conf.xml and start the kyuubi, the error happened.So i discard the  kerberos auth and delete the keytab and pricipal in the spark-defaults-conf.xml and start the kyuubi server, the message in log display when i make the zk.ha true, kyuubi will use kerberos to auth and the error is there is no spark.yarn.keytab.As a  result,how do i connect to zeekeeper without kerberos? My zookeeper is no auth.

**To Reproduce**
1. Configurations
    frist i export environment:
    export HADOOP_CONF_DIR=/etc/hadoop/conf
    export SPARK_HOME=/opt/spark/spark-2.1.3-bin-hadoop2.6
    second i editor spark-deaults.conf file to add these:
    spark.yarn.principal ***/***@HADOOP.COM
    spark.yarn.keytab ****.keytab
2. Environments
    spark:spark-2.3-bin-hadoop2.7
    linux:centos7
    java:1.8 
    kyuubi:master
    hadoop: CDH-5.13.3
    zookeeper:3.4.5+cdh5.13.3
3. Operations
    /opt/spark/kyuubi-0.7.0-bin-spark-2.1.3/bin/start-kyuubi.sh 
   --master yarn 
   --conf spark.kyuubi.ha.enabled=true 
   --conf spark.kyuubi.ha.zk.quorum=134.64.14.231,134.64.14.232,134.64.14.233 
   --conf spark.kyuubi.ha.zk.client.port=2181 
   --conf spark.kyuubi.authentication=KERBEROS 
   --conf spark.driver.memory=20g 
   --conf spark.hadoop.fs.hdfs.impl.disable.cache=true 
   --conf spark.executor.heartbeatInterval=30s
    19/07/25 14:56:02 INFO state.ConnectionStateManager: State change: CONNECTED
    19/07/25 14:56:02 ERROR client.ZooKeeperSaslClient: An error: 
    (java.security.PrivilegedActionException: javax.security.sasl.SaslException: GSS initiate failed 
    [Caused by GSSException: No valid credentials provided (Mechanism level: Server not found in 
    Kerberos database (7) - UNKNOWN_SERVER)]) occurred when evaluating Zookeeper Quorum 
    Member's received SASL token. This may be caused by Java's being unable to resolve the 
    Zookeeper Quorum Member's hostname correctly. You may want to try to adding '- 
    Dsun.net.spi.nameservice.provider.1=dns,sun' to your client's JVMFLAGS environment. 
    Zookeeper Client will go to AUTH_FAILED state.
    19/07/25 14:56:02 ERROR zookeeper.ClientCnxn: SASL authentication with Zookeeper Quorum 
    member failed: javax.security.sasl.SaslException: An error: 
    (java.security.PrivilegedActionException: javax.security.sasl.SaslException: GSS initiate failed 
    [Caused by GSSException: No valid credentials provided (Mechanism level: Server not found in 
    Kerberos database (7) - UNKNOWN_SERVER)]) occurred when evaluating Zookeeper Quorum 
    Member's received SASL token. This may be caused by Java's being unable to resolve the 
    Zookeeper Quorum Member's hostname correctly. You may want to try to adding '- 
    Dsun.net.spi.nameservice.provider.1=dns,sun' to your client's JVMFLAGS environment. 
    Zookeeper Client will go to AUTH_FAILED state.
    19/07/25 14:56:02 ERROR curator.ConnectionState: Authentication failed
    Error: Starting Kyuubi by client yaooqinn.kyuubi.service.ServiceException: Unable to create 
    Kyuubi namespace /kyuubiserver on ZooKeeper
    Run with --help for usage help or --verbose for debug output
    19/07/25 14:56:02 INFO server.KyuubiServer: Shutting down KyuubiServer
    19/07/25 14:56:02 INFO util.ShutdownHookManager: Shutdown hook called
    **Expected behavior**

**Screenshots**

**Additional context**

**Comment by yaooqinn** [comment]
This might not be problem of kyuubi or zk. It is the keytab that you use may have issues. try google or may see this https://stackoverflow.com/questions/13850252/cannot-get-kerberos-service-ticket-krbexception-server-not-found-in-kerberos-d/15987751

**Comment by SunFlowerY1** [comment]
Thank you for you great answer, there is a little doubt about it, i try to make the ha is false and server can login successfully with the keytab i supply.Only when i make the ha is true,the error happened and i also try to make the auth is none and ha is true, there is also the same error.So i want to make sure is really the problem of keytab?

**Comment by SunFlowerY1** [comment]
> This might not be problem of kyuubi or zk. It is the keytab that you use may have issues. try google or may see this https://stackoverflow.com/questions/13850252/cannot-get-kerberos-service-ticket-krbexception-server-not-found-in-kerberos-d/15987751

**Comment by SunFlowerY1** [comment]
In addition, my zookeeper is not configured kerberos auth.I wonder if that's going to be a problem.

**Comment by yaooqinn** [comment]
we are not reaching zk yet, may be only kdc part. I am not sure whether a non-kerberized zk will reject anyone who has a kerberos ticket or not. Currently I guess the problem is that the keytab you specified is not able to auth via kdc. Of course, as a workaround, skipping this part might work.

**Comment by SunFlowerY1** [comment]
OK，thank you very much!

**Comment by SunFlowerY1** [comment]
The problem has been solved.The problem is the keytab that kyuubi server use to connect zk. It seems that the kyuubi server will use kerberos auth to connect zk.And the zkCli's default keytab is something like zookeeper/******.When i configure the zkCli and add the correct keytab in kdc,the problem is solved.
