### ISSUE TITLE
run sql sricpt

### ISSUE THREAD

**Issue by yuangjiang** [yaooqinn/kyuubi#223]
hi! 
kyuubi can run spark sql sript now ? i try to run spark sql script and Passing parameters to script  but not runing. is issues ?

**Comment by yaooqinn** [comment]
yes

**Comment by yuangjiang** [comment]
i how to solve this problem ？i want to use kyuubi run spark sql script need Passing parameters by script. i envirement is CDH 5.14 .

**Comment by yaooqinn** [comment]
read the doc first

**Comment by yuangjiang** [comment]
can you give me a doc url ?
