### ISSUE TITLE
support for UDF ?

### ISSUE THREAD

**Issue by parisni** [yaooqinn/kyuubi#225]
Hello

Spark 2.4.4
kyuubi 0.8.0

I tried to add UDF (it is working in spark-shell) within kyuubi by :
1. passing the jar containing spark udf to kyuuby --jars and restarting it
2. creating the function in the user session: 
3. runing the function

I get that error:

```
org.apache.spark.sql.AnalysisException: No handler for UDF/UDAF/UDTF 'org.my.DateDiff'; l
```
so my question: how to make spark udf working within kyuubi ?

this answer https://stackoverflow.com/a/56970800/3865083 says spark only support hive udf which looks paradoxal.

thanks

**Comment by yaooqinn** [comment]
I guess you can make `bin/spark-sql` work for spark udf first

**Comment by parisni** [comment]
I made this working. It is paradoxal but in sql mode, only hive-udf works. 
So I have to rewrite my spark-udf in the hive API. and then:
- build the jar and pass it with kyuubi `--jars`
- in the client, run `create temporary function udfquote as 'org.my.udf.UDFquote';`
- then `select udfqute(c1)` works as expected

**Comment by parisni** [comment]
this repository show the various way of implementing udf and also hive-udf
https://github.com/curtishoward/sparkudfexamples
