### ISSUE TITLE
使用Kyuubi执行一条简单SQL,执行时间没有SparkThriftServer 快

### ISSUE THREAD

**Issue by EdwardLiao008** [yaooqinn/kyuubi#229]
1. Hello, 我这边执行了一条简单SQL语句：SELECT 某张分区表。 我看Stage只花了3s,但是到返回结果却花了1分钟左右，有时更长。相同SQL我用SparkThriftServer  **使用相同配置项** 只花了6s左右。 不知道是不是我Kyuubi配置的参数有问题，下面是我的启动参数
1.sh start-kyuubi.sh  --master yarn 
--deploy-mode client 
--driver-memory 5g  
--conf spark.kyuubi.frontend.bind.port=10009 
--conf spark.dynamicAllocation.enabled=true 
--conf spark.dynamicAllocation.minExecutors=1 
--conf spark.dynamicAllocation.maxExecutors=10 
--conf spark.dynamicAllocation.cachedExecutorIdleTimeout=120s

**Comment by yaooqinn** [comment]
lazy SparkContext
