### ISSUE TITLE
SparkSQLEngineApp can't run in IDEA

### ISSUE THREAD

**Issue by huzekang** [yaooqinn/kyuubi#237]
![image](https://user-images.githubusercontent.com/18548053/86251775-e1981700-bbe4-11ea-838d-fcbc890e5512.png)

**Comment by yaooqinn** [comment]
Hi @huzekang Thanks for reporting this. The Kyuubi version 1.0.0 is still in progress, it brings tremendous changes, it is kind of difficult for us to take care of everything when the car is running. If you are interested, you can help with this issue, thanks in advance.
