### ISSUE TITLE
Support for Spark-3.0.0

### ISSUE THREAD

**Issue by kongtrio** [yaooqinn/kyuubi#238]
Spark 3.0 was released on Jun 18, 2020. It brings many new features that greatly enhance task performance. But when I review the Kyuubi code, found it not to support Spark 3.0. There are some Kyuubi class dependency Spark 2.4.5's class that is deprecated in Spark 3.0.
So do you have plans for compatibility with Spark3.0? If yes, can you tell me the approximate time?

**Comment by yaooqinn** [comment]
yea, spark 3.0 is exciting. are you interested in working on this?

**Comment by kongtrio** [comment]
> yea, spark 3.0 is exciting. are you interested in working on this?

I'm so pleasured. Could you invite me to the Kyuubi Wechat group to discuss this? Or give me your Wechat number.
