### ISSUE TITLE
对spark3.0的支持有具体的时间线吗

### ISSUE THREAD

**Issue by servlet001** [yaooqinn/kyuubi#245]
我想知道目前对spark3.0的支持目前进度如何？谢谢！

**Comment by yaooqinn** [comment]
It is still in progress and not fully completed, but the master can actually work for spark 3.0 with now.
You can follow the step to run
## build it
```
mvn clean install -pl '!:kyuubi-thrift,!:kyuubi-server'

```

## start it
```
bin/kyuubi.sh start
```

then you can connect and run some test with beeline tool, etc

I appreciate for you help

**Comment by qlmbeck** [comment]
你好，请问你是怎么连上kyuubi的，他要我输入账号密码，这个要在哪里设置
