### ISSUE TITLE
Whta is the username and password?

### ISSUE THREAD

**Issue by qlmbeck** [yaooqinn/kyuubi#247]
I use beeline to connect kyuubi, the URI is jdbc:hive2//ip:10009，then it asks me to enter username and password.I don't know how to solve it，can anyone help me?

**Comment by yaooqinn** [comment]
version?

**Comment by qlmbeck** [comment]
I test the releases v0.8.0-rc2  and v0.6.2 ,and all of them failed.

**Comment by yaooqinn** [comment]
how did you setup authentication?

**Comment by qlmbeck** [comment]
I use $KYUUBI_HOME/bin/start-kyuubi.sh --conf spark.kyuubi.authentication=NONE to start it ,I set proxy user in CDH ,but failed.

**Comment by qlmbeck** [comment]
Sorry,my jdbcurl is jdbc:hive2://localhost:10009,I replaced 'localhost' to the ip just now,and it succed.Thank fro your help.
