### ISSUE TITLE
kyuubi 在apache包中，SparkSQLSessionManager没有了SparkSessionWithUGI的multi context功能吗？

### ISSUE THREAD

**Issue by shenbinglife** [yaooqinn/kyuubi#249]
SparkSessionWithUGI 通过为不同用户创建SparkContext实现资源隔离，在SparkSQLSessionManager并没有这个功能？ 
我理解的是yaooqinn.kyuubi 应该尽量迁移使用org.apache.kyuubi  ， 对吗？

**Comment by yaooqinn** [comment]
> SparkSessionWithUGI 通过为不同用户创建SparkContext实现资源隔离，
是的，这是老的架构，基于user-> sc的映射实现。

> 在SparkSQLSessionManager并没有这个功能？
是的。在新的架构下，我们采取了进程调度，sc不再在server进程中，而SparkSQLSessionManager是计算侧子进程的一部分。
可以看服务端还有KyuubiSessionManager这个实现。

> 我理解的是yaooqinn.kyuubi 应该尽量迁移使用org.apache.kyuubi ， 对吗？

对

**Comment by shenbinglife** [comment]
每当用户第一次连接：
KyuubiSessionManager.open 创建SparkSubmit进程，提交一个SparkEngine 作业 到Yarn上。SparkEngine 启动时，创建一个SparkContext和FrontService，把FrontService的host: port注册到ZK中，KyuubiSessionManager 通过读取ZK获得FrontService的地址，并通过ThriftClient创建连接。

当用户第二次连接：
从ZK中取出已存在的SparkEngine的FrontService的 host和port，通过ThriftClient连接上去，打开远程会话。 

不同的用户提交的SparkEngine作业会资源隔离。

麻烦请评价一下是否理解正确

**Comment by yaooqinn** [comment]
过程基本正确。
1）不一定需要Yarn，其他k8s也ok。
2）如果有外部的zk的话，若干（N）个kyuubi server也可以共享（1-N）SparkSQLEngine，所以也不一定会新建。

**Comment by shenbinglife** [comment]
谢谢你的帮助。 

我对kyuubi-thrift 的模块并不理解， 出于什么目的创建了这个模块，而不是引用hive-service-rpc 的maven包？是有自定义的修改吗？
