### ISSUE TITLE
Driver is not terminated immediately after Kyuubi server is stopped

### ISSUE THREAD

**Issue by Honglun** [yaooqinn/kyuubi#304]
when we modify the configuration of kyuubi and then restart the kyuubi server，we have to manually kill the yarn app or the SparkSubmit process, otherwise, the driver will use the old configuration, which is not what we expect.

**Comment by yaooqinn** [comment]
https://kyuubi.readthedocs.io/en/latest/quick_start/quick_start.html#stopping-kyuubi
this is in doc

Or do you have a better idea?

**Comment by yaooqinn** [comment]
For the case of failover, recreating a Kyuubi server is light

**Comment by Honglun** [comment]
When Kyuubi server, can all drivers be terminated at the same time? Or add an option to terminate all drivers at once

**Comment by yaooqinn** [comment]
In HA mode or just a failover case, a server terminated does not mean that the engines should stop too, they can still be reached by other peers or a recovered server.

we have provided several configs in the doc for an engine's lifecycle, you can check that.

BTW, I am quite open with a better idea for managing engines

**Comment by Honglun** [comment]
I see what you mean.  I'm not talking about changing the current design, I mean add a new feature that will allow us to stop all the engines in time.

**Comment by yaooqinn** [comment]
> I see what you mean. I'm not talking about changing the current design, I mean add a new feature that will allow us to stop all the engines in time.

The new feature would be planned into v1.1, it would be better if you happen to have a solution

**Comment by yaooqinn** [comment]
This is partially supported now for the `connection` share level egnines

**Comment by yaooqinn** [comment]
Keep it open and retarget it to v1.2.0 to see if we can get a better idea for this. cc @ulysses-you as the release manager of v1.1.0

**Comment by ulysses-you** [comment]
Sorry for the vert late reply. The idea looks like useful.

The behavior more like `decommission`which is a liitle different with `stop`, that means the whole Kyuubi is not available and the all reousrce (not only the application but also some tmp file if exists) of Kyuubi will be released.

Maybe we can expose a new script, and user can execute like `sh decommission.sh`. I hope it could be done in v1.2.0 but it would be great if you can make a PR for this. : )

**Comment by Honglun** [comment]
'ServiceDiscovery' create a 'stopTag' node in zookeeper during initialization, and add watchers on the 'stopTag' node for all the servers and engines. When we want to stop all the servers, we only need to remove the 'stopTag' node.
How about this one?

**Comment by yaooqinn** [comment]
IMO, the use case here is very simple, that is, whether we want all of the engines to be terminated after all servers stopped `manually`.
We don't need to think about the case that servers are stopped by irresistible forces, like hardware failure, etc..

So here we just need a trigger for the `bin/kyuubi stop`, for example, `bin/kyuubi stop egines`, to stop server and engines in a single run.

Add for the builtin-zkserver inside Kyuubi, we can simply stop engines at the same time as it's only for test purposes.

**Comment by yaooqinn** [comment]
Also with this option, we can invalidate all current engines which have nothing related to servers

**Comment by Honglun** [comment]
> IMO, the use case here is very simple, that is, whether we want all of the engines to be terminated after all servers/the last server stopped `manually`.
> We don't need to think about the case that servers are stopped by irresistible forces, like hardware failure, etc..
> 
> So here we just need a trigger for the `bin/kyuubi stop`, for example, `bin/kyuubi stop egines`, to stop server and engines in a single run.
> 
> Add for the builtin-zkserver inside Kyuubi, we can simply stop engines at the same time as it's only for test purposes.

Understand.

**Comment by Honglun** [comment]
I use the above temporary solution until we find a better idea. Here are some pseudo-code:
`zk.create(stopTagNode)`
`zk.usingWatcher(watcher)  watcher=>Watcher.Event.EventType.NodeDeleted)  => sys.exit(0)`
`bin/kyuubi stopAll => ServerManager => main => zk.delete(stopTagNode)`

**Comment by yaooqinn** [comment]
Sorry, I still do know why we should introduce the `stopTagNode` here?

The `serviceNode` itself is enough for the retiring of both Kyuubi Servers and Engines.


When the  `serviceNode` is deleted, the Engine can use a watcher to self terminate just like the server's behavior right now. 

A `serviceNode` is could be identified by `zkAddress` - `namespace` - `service host` -` service port` - `KYUUBI_VERSION`

```scala
bin/kyuubi service <create|get|delete|list>  <server|engine> --zkAddress ... --namespace ... --user ... --host ... --port ... --version

Operations:
    - create  -  expose a service to a namespace, this case is rare but sometimes we may want one server to be reached in 2 or more namespaces by different user groups
    - get - get the service node info
    - delete - delete the specified serviceNode
    - list - list all the service nodes for a particular domain
Role:
    - server default
    - engine 

Args:

   --zkAddress  - one of the zk ensemble address, using kyuubi-defaults/conf if absent
   --namespace  -  the namespace, using kyuubi-defaults/conf if absent
   --user - 
   --host
   --port
   --version
```

Then we can use these basic commands to fulfill other composite needs, for example deleteAll is `list + foreach(delete)`

WDYT, @ulysses-you @pan3793

**Comment by Honglun** [comment]
Ignore my idea, I just wanted to use this temporary solution to implement this feature quickly for ease of deployment. BTW, I found that we may want to stop the node gracefully, so I create a new node for stopping all engines and servers.

**Comment by yaooqinn** [comment]
`Stopping the node gracefully` can also be accomplished with `serviceNode` deletions, and the service itself shall always become offline first then self terminated after no client activities. 

Do you have time to help with these features？@Honglun

I think we can do these separately with a brunch of PRs

**Comment by Honglun** [comment]
I think we should offer an additional option to stop the service immediately. We can not wait a idle session until it is timeout if we want stop the server immediately.

**Comment by pan3793** [comment]
> I think we should offer an additional option to stop the service immediately. We can not wait a idle session until it is timeout if we want stop the server immediately.

Hi @Honglun, if I understand correctly, @yaooqinn design already covered this request.

The following command will delete the engine zk node, then the engine will notified by watcher, and shutdown gracefully.
```
bin/kyuubi service delete engine --zkAddress ... --namespace ... --user ... --host ... --port ... --version ...
```

**Comment by Honglun** [comment]
> when we modify the configuration of kyuubi and then restart the kyuubi server，we have to manually kill the yarn app or the SparkSubmit process, otherwise, the driver will use the old configuration, which is not what we expect.

If I want to deal with the case above, I need run the two commands:
`bin/kyuubi service deleteAll servers`
`bin/kyuubi service deleteAll engines`

@yaooqinn @pan3793 What I want is to make the configuration take effect immediately, I don't wanna wait, but the first command will stop gracefully which may takes a lot of time. That's what I'm confused about.

**Comment by yaooqinn** [comment]
> which may take a lot of time

Is this mean that there are still running queries but no matter what you just want to kill them? In this case, we can add one more argument `--force` just like `kill -9`

**Comment by pan3793** [comment]
How about rolling restart `servers`? And then `deleteAll engines`

**Comment by turboFei** [comment]
`KYUUBI_VERSION`
> 
> ```scala
> bin/kyuubi service <create|get|delete|list>  <server|engine> --zkAddress ... --namespace ... --user ... --host ... --port ... --version
> 
> Operations:
>     - create  -  expose a service to a namespace, this case is rare but sometimes we may want one server to be reached in 2 or more namespaces by different user groups
>     - get - get the service node info
>     - delete - delete the specified serviceNode
>     - list - list all the service nodes for a particular domain
> Role:
>     - server default
>     - engine 
> 
> Args:
> 
>    --zkAddress  - one of the zk ensemble address, using kyuubi-defaults/conf if absent
>    --namespace  -  the namespace, using kyuubi-defaults/conf if absent
>    --user - 
>    --host
>    --port
>    --version
> ```
> 
> Then we can use these basic commands to fulfill other composite needs, for example deleteAll is `list + foreach(delete)`
> 

I will try to implement it.

**Comment by Honglun** [comment]
Can we use `Watcher.Event.EventType.NodeDataChanged` for `stopGracefully`, and `Watcher.Event.EventType.NodeDeleted` for `stopForce` ?

**Comment by yaooqinn** [comment]
On second thought, if all servers stop and close their connections with an engine, it should be able to stop quickly with a very short delay. Consequently, it might be necessary to introduce a `force` stop.
