### ISSUE TITLE
Spark Engine should support windows

### ISSUE THREAD

**Issue by Honglun** [yaooqinn/kyuubi#306]
Easy to test for developers using Windows.

**Comment by yaooqinn** [comment]
all you going to run `mvn test` on win?

**Comment by Honglun** [comment]
Running Kyuubi server

**Comment by yaooqinn** [comment]
could you help with this？ I don't have any win env

**Comment by Honglun** [comment]
OK, I will fix this.

**Comment by yaooqinn** [comment]
Appreciate it
