### ISSUE TITLE
[Feature Request] Support run kyuubi-server in the foreground

### ISSUE THREAD

**Issue by pan3793** [yaooqinn/kyuubi#312]
**Is your feature request related to a problem? Please describe.**
Currently, we can use `kyuubi start` to run `kyuubi-server` at background, so we can't manage it's lifecycle by supervision systems like `supervisord`, `systemd`.

**Describe the solution you'd like**
New command `kyuubi run` to run `kyuubi-server` in frontend. It's actually what Trino (formerly PrestoSQL) does. https://trino.io/docs/current/installation/deployment.html#running-trino

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by yaooqinn** [comment]
LGTM
