### ISSUE TITLE
Avoiding using commons-lang2

### ISSUE THREAD

**Issue by pan3793** [yaooqinn/kyuubi#340]
**Describe the bug**
There are some usage of `commons-lang2` in `kyuubi-common`, we need to migrate them to `commons-lang3`

**To Reproduce**
1. Configurations
2. Environments
3. Operations

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yaooqinn** [comment]
lgtm

**Comment by yaooqinn** [comment]
please send a PR.

**Comment by pan3793** [comment]
> please send a PR.

Local testing ...
