### ISSUE TITLE
Does session have a timeout cleanup mechanism?

### ISSUE THREAD

**Issue by Honglun** [yaooqinn/kyuubi#347]
**Is your feature request related to a problem? Please describe.**
I can't find any configuration or code for this. If the user forgets to close the session, the Engine lives forever.

**Comment by yaooqinn** [comment]
https://kyuubi.readthedocs.io/en/latest/deployment/settings.html#session

**Comment by Honglun** [comment]
This will not work if the user does not actively close the session. See 'getOpenSessionCount' down here:
`override def run(): Unit = {
        while (getOpenSessionCount > 0 ||
          System.currentTimeMillis - latestLogoutTime < idleTimeout) {
          TimeUnit.MILLISECONDS.sleep(interval)
        }
        info(s"Idled for more than $idleTimeout ms, terminating")
        sys.exit(0)
      }`

**Comment by yaooqinn** [comment]
kyuubi.session.timeout？

> This will not work if the user does not actively close the session. See 'getOpenSessionCount' down here:
> `override def run(): Unit = { while (getOpenSessionCount > 0 || System.currentTimeMillis - latestLogoutTime < idleTimeout) { TimeUnit.MILLISECONDS.sleep(interval) } info(s"Idled for more than $idleTimeout ms, terminating") sys.exit(0) }`

**Comment by Honglun** [comment]
Yes, I missed this configuration. But there is still a problem, 'session.closeExpiredOperations' will constantly update the values of '_lastAccessTime' and '_lastIdleTime', so the session can't be closed. Method  'closeExpiredOperations' should remove 'withAcquirerease'.
https://github.com/yaooqinn/kyuubi/blob/e4d9390a74a33f09eb25b7f6ab9174c25d00b0e2/kyuubi-common/src/main/scala/org/apache/kyuubi/session/SessionManager.scala#L162

**Comment by yaooqinn** [comment]
nice catch！ would you like to fix  that？

**Comment by Honglun** [comment]
OK

**Comment by Honglun** [comment]
@yaooqinn I didn't think it through last time. After the last expired Handle has been cleaned, the 'lastIdleTime' needs to be updated. Can you help re-open the issue?
