### ISSUE TITLE
FetchOrientation.FETCH_FIRST is not handled properly

### ISSUE THREAD

**Issue by pan3793** [yaooqinn/kyuubi#360]
**Describe the bug**

In `SparkOperation`, all `order` actually  are treat as `FETCH_NEXT`

```
  override def getNextRowSet(order: FetchOrientation, rowSetSize: Int): TRowSet = {
    validateDefaultFetchOrientation(order)
    assertState(OperationState.FINISHED)
    setHasResultSet(true)
    val taken = iter.take(rowSetSize)
    RowSet.toTRowSet(taken.toList, resultSchema, getProtocolVersion)
  }
```

**To Reproduce**
Use HUE to connect Kyuubi server and run a query, then export the result to csv, we found the records showed in web page is lost in exported data.

**Expected behavior**
Hue can export all records of query result.

**Screenshots**

**Additional context**

**Comment by yaooqinn** [comment]
For fetch first, can we cache the result at the Kyuubi server side?

**Comment by pan3793** [comment]
Personally, I prefer to cache the result in Spark Driver side. 

Considered Kybuui server will manage several sessions, if all query results cache on Kyuubi server, it will consume lots of memories, and cause high OOM risk. If Kyuubi server failover, the cache lost. If one session exit or crash, we need do some clean work to release the associated result cache.

@wangyum I remember you mentioned some optimization works on driver side query result in previous tech share but no detail description, would you like share more details on this?
