### ISSUE TITLE
DBeaver try conect 'jdbc:hive2//ip:port' fail

### ISSUE THREAD

**Issue by zwangsheng** [yaooqinn/kyuubi#384]
**Describe the bug**
DBeaver conect 'jdbc:hive2//ip:port' fail

**To Reproduce**
1. Configurations
no big change
set kyuubi.frontend.bind.port=10008
2. Environments
all default
3. Operations
start kyuubi
and try use dbeaver to contect hive2
contect refuse

**Expected behavior**
contect success

**Screenshots**

**1**
![1614653916](https://user-images.githubusercontent.com/52876270/109590297-b1739000-7b46-11eb-86ee-202d38bb1761.png)
**2**
![1614653468](https://user-images.githubusercontent.com/52876270/109589848-f2b77000-7b45-11eb-8c0b-642e18814f89.png)
**3**
![1614654634](https://user-images.githubusercontent.com/52876270/109591172-08c63000-7b48-11eb-9892-f5698b0fd803.png)

**Additional context**
can see by the 1.picture and log, Server start success and exposing JDBC connection at: jdbc:hive2://localhost.localdomain:10008/
then see the result of use cmd netstat -tunlp(picture 2), see server Local Address is 127.0.0.1, so this port can not be contect by outside client
And i try to change the conf kyuubi.frontend.bind.host=ip, result is picture 3 - server can not start 
Put aside these things，i see a Blog talk about remote server had the same proble and try use conf to fix，according to kyuubi doc set kyuubi.frontend.bind.host=0.0.0.0 can solve this problem

**Comment by pan3793** [comment]
The ip bind logic is:
1. if `frontend.bind.host` is provided, use `InetAddress.getByName(host)` to detect which ip to bind;
2. otherwise, bind to `InetAddress.getLocalHost()`

You can write a simple Java code to test on your machine of these two methods' behavior. And we can discuss here if you have some suggestion for the ip bind logic.

**Comment by zwangsheng** [comment]
i try config kyuubi.frontend.bind.host=ip still fail, and i run the progress for `InetAddress.getByName(ip)` got /ip, may it lead to this problem? And I wonder if it is possible not to bind the host, just listen to the specified port

**Comment by pan3793** [comment]
> And I wonder if it is possible not to bind the host, just listen to the specified port

Technically it's impossible, the socket must bind on at least one network card, specifically, `0.0.0.0` means bind to all network cards. And please make sure you have sufficient permissions to bind your socket on `InetAddress.getByName(ip)`.

**Comment by zwangsheng** [comment]
> Technically it's impossible, the socket must bind on at least one network card, specifically, `0.0.0.0` means bind to all network cards. And please make sure you have sufficient permissions to bind your socket on `InetAddress.getByName(ip)`.

i try fix the host and now without set `kyuubi.frontend.bind.host=ip`, i can connect to hive2.
But i still have question about host
![IMG20210303_181920](https://user-images.githubusercontent.com/52876270/109791047-ff72bb80-7c4c-11eb-92d5-e7a11125164c.png)
Is the registered node normal?

**Comment by pan3793** [comment]
It's a reasonable result.
