### ISSUE TITLE
Clean up discovery service before engine stop in connection share level

### ISSUE THREAD

**Issue by ulysses-you** [yaooqinn/kyuubi#386]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
In connection level, we will release engine if the session connection is closed but we don't clean up the discovery service (i.e. the namespace in zookeeper). That may cause the disk stress after running a long time.

**Additional context**

**Comment by yaooqinn** [comment]
Looks cool！

**Comment by yaooqinn** [comment]
Mind take a lot at the flaky test https://travis-ci.org/github/yaooqinn/kyuubi/jobs/761385865, seems related
