### ISSUE TITLE
Error running 'select function' command

### ISSUE THREAD

**Issue by Honglun** [yaooqinn/kyuubi#397]
**Describe the bug**

**To Reproduce**
1. Configurations
2. Environments
3. Operations

**Expected behavior**

select tmp_db.hello('mike')
Run the above SQL causes an error:
Error: Error operating EXECUTE_STATEMENT: org.apache.spark.sql.AnalysisException: cannot resolve '`tmp_db.hello(mike)`' given input columns: [tmp_db.hello(mike)];;
And SQL like this: select 'tmp_db.hello'

We see a problem here
https://github.com/yaooqinn/kyuubi/blob/master/externals/kyuubi-spark-sql-engine/src/main/scala/org/apache/kyuubi/engine/spark/operation/ExecuteStatement.scala#L78

**Screenshots**

**Additional context**

**Comment by yaooqinn** [comment]
can it pass on Kyuubi 1.0.3?

**Comment by Honglun** [comment]
> can it pass on Kyuubi 1.0.3?

Yes

**Comment by yaooqinn** [comment]
could you help to verify https://github.com/yaooqinn/kyuubi/tree/397 for https://github.com/yaooqinn/kyuubi/pull/400
