### ISSUE TITLE
Add LICENCE-binary to respect all upstream artifacts and satisfy the Apache Law

### ISSUE THREAD

**Issue by yaooqinn** [yaooqinn/kyuubi#423]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Example Here

https://github.com/apache/spark/blob/4d47ac4b4b20a475c2f416c7d614318b31323041/LICENSE-binary

or

https://github.com/apache/submarine/blob/master/LICENSE-binary
**Describe alternatives you've considered**

**Additional context**

**Comment by yaooqinn** [comment]
Hi @MyLanPangzi, can you help us with this? also cc @pan3793

**Comment by pan3793** [comment]
Should we also need update `LICENSE`?

**Comment by yaooqinn** [comment]
yes if necessary
