### ISSUE TITLE
Can not cancel SQL job if the timeout value is small

### ISSUE THREAD

**Issue by ulysses-you** [yaooqinn/kyuubi#456]
### 1. Describe the bug

We kown, in short Spark will compile the SQL to RDD then use `DAGScheduler` to execute the each partiiton. If the SQL string is large (probable over hundred lines), the SQL compilation may take a few time(several seconds). At this time with small query timeout limit(also several seconds), `sc.cancelJobGroup` may not find the SQL job in `DAGScheduler` since it's still in SQL compilation. As the result, the SQL job leak.

A simple pipeline:
```
a thread: 1) SQL string -> 2) SQL compilation -> 3) DAGScheduler -> ...

b thread: 1) cancelJobGroup -> 2) DAGScheduler
```
When thread b at step 2, the thread a may stay at step 2, so can not cancel the job correctly.

The reason about the slow SQL compilation can be:
1. the SQL it is large enough
2. the slow rpc with Hive
3. since the Hive catalog in Spark driver use the global lock, it might be a reason in some case.

Some option to solve such case:
1. interrupt the SQL compliation thread and then do cancelJobGroup
2. check job is exits for a memont until job exists and then do cancelJobGroup

**Comment by yaooqinn** [comment]
let's add   ` Option(getBackgroundHandle).foreach(_.cancel(true))` to `cleanup`  of `SparkOperation`
