### ISSUE TITLE
Support  configurable initialize sql statement for engine startup

### ISSUE THREAD

**Issue by yaooqinn** [yaooqinn/kyuubi#457]
### 1. Describe the feature

Currently,  the engine uses hardcoded `show databases` to force initialization with catalog eagerly bootstrapping too

we  can make it configurable with a comma separate query list and `select current_database()` might be used as default since it's more lightweight than `show databases` in real-world cases

### 2. Motivation

 Initialize SQLs can meet some particular cases when users may want something to be activated by default before queries.

### 3. Describe the solution

`kyuubi.engine.initialize.sql` can be introduced to achieve this goal  with a default value `SELECT CURRENT_DATABASE()`

**Comment by yaooqinn** [comment]
CC @turboFei  Can you help with this?

**Comment by turboFei** [comment]
sure, with pleasure
