### ISSUE TITLE
Need exclude more files to precent flake ` unapproved license`  when building kyuubi

### ISSUE THREAD

**Issue by turboFei** [yaooqinn/kyuubi#467]
### 1. Describe the bug

I met this exception when building kyuubi.
```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:20 min
[INFO] Finished at: 2021-03-28T00:40:18+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.13:check (default) on project kyuubi-spark-sql-engine: Too many files with unapproved license: 1 See RAT report in: /Users/fwang12/todo/kyuubi/externals/kyuubi-spark-sql-engine/target/rat.txt -> [Help 1]
```
Then I check the content of that file.

![image](https://user-images.githubusercontent.com/6757692/112727772-0a282400-8f5f-11eb-8099-12b5ff9bbd39.png)

### 2. Environments

mac + IDEA

### Workaround
might this operation crashed and failed to cleanup log gracefully.
 exclude more files

**Comment by yaooqinn** [comment]
yup, in case of failures, we need to exclude them. and also we should mv these files to `target`
