### ISSUE TITLE
Fix broken link in https://github.com/yaooqinn/kyuubi/blob/master/docs/index.rst

### ISSUE THREAD

**Issue by yaooqinn** [yaooqinn/kyuubi#515]
#### 2.1 Versions

- Kyuubi
  - [ ] 1.1.0
  - [ ] 1.0.3
  - [ ] 0.8.x and earlier 

- Spark
  - [ ] 3.1.x
  - [ ] 3.0.x
  - [ ] 2.4.x and earlier 

#### 4.2 Log of the corresponding engine

**Comment by pan3793** [comment]
Would you like to take this? cc @BetaCat0
