### ISSUE TITLE
Incorrect spark version in quick start

### ISSUE THREAD

**Issue by yaooqinn** [yaooqinn/kyuubi#516]
### 1. Describe the bug

![image](https://user-images.githubusercontent.com/8326978/114499861-89a13d00-9c59-11eb-882b-c9889d6c1929.png)

It should be 3.0 and above

#### 2.1 Versions

- Kyuubi
  - [ ] 1.1.0
  - [ ] 1.0.3
  - [ ] 0.8.x and earlier 

- Spark
  - [ ] 3.1.x
  - [ ] 3.0.x
  - [ ] 2.4.x and earlier 

#### 4.2 Log of the corresponding engine

**Comment by pan3793** [comment]
@cookcocck Would you like to pick this task?
