### ISSUE TITLE
spark.ui.proxyBase will be overwritten each time after submit an yarn app

### ISSUE THREAD

**Issue by yaooqinn** [yaooqinn/kyuubi#72]
this conf is used by spark‘s  live web ui to map ui root address for tabs, pages, and any other links on the spark web ui
https://github.com/apache/spark/blob/v2.3.0/core/src/main/scala/org/apache/spark/ui/UIUtils.scala#L153

kyuubi submit multi yarn apps in a single jvm, but spark treat this conf as System Props, so it will be overwritten each time, which will cause ui mapping isusse when visiting ui.
This means you need correct the proxy address with the right app_id on each click

a suitable solution may be found here https://github.com/yaooqinn/multi-tenancy-spark/commit/aeb0a8332240a2793f57dea4ddfdbcde8ed20fde

i will work on this later

**Comment by kevin00chen** [comment]
方便留个联系方式么，最近在尝试Kyuubi

**Comment by yaooqinn** [comment]
wechat id is as same as github id

**Comment by sqlwindspeaker** [comment]
I tried another approach, which may be not so elegant but may be enough for within company.

I found that the url from Yarn is current, so if we suppose the first applicationId in url is correct, then we can use this to get applicationId and overwrite the uiRoot from System props.

The reason not getting this from current spark context is that UIUtils is an object, we should use global env to get current spark context. which I'm not sure if there will be some problem in high parallelism

**Comment by yaooqinn** [comment]
@sqlwindspeaker in which part we can reset system props?

**Comment by sqlwindspeaker** [comment]
Sorry i made a mistake yesterday, I was thinking that we can get the applicationId from the URL in the HttpServletRequest, but actually not. applicationId is passed to the proxy, and the final URL does not contains this message. So I finally use HttpServletRequest.setAttribute to approach.

```
// write appId
 def attachPage(page: WebUIPage): Unit = {
    val pagePath = "/" + page.prefix
    val renderHandler = createServletHandler(pagePath,
      (request: HttpServletRequest) => {
        request.setAttribute("spark.app.id", conf.get("spark.app.id"))
        page.render(request)
      }, securityManager, conf, basePath)
    val renderJsonHandler = createServletHandler(pagePath.stripSuffix("/") + "/json",
      (request: HttpServletRequest) => page.renderJson(request), securityManager, conf, basePath)
    attachHandler(renderHandler)
    attachHandler(renderJsonHandler)
    val handlers = pageToHandlers.getOrElseUpdate(page, ArrayBuffer[ServletContextHandler]())
    handlers += renderHandler
  }

```
```
// read appId
  def uiRoot(request: HttpServletRequest): String = {
    // Knox uses X-Forwarded-Context to notify the application the base path
    val knoxBasePath = Option(request.getHeader("X-Forwarded-Context"))
    // SPARK-11484 - Use the proxyBase set by the AM, if not found then use env.

    val yarnAppId = request.getAttribute("spark.app.id").asInstanceOf[String]

    logInfo(s"yarnAppId is: $yarnAppId")

    if (yarnAppId.startsWith("application_")) {
      s"/proxy/$yarnAppId"
    } else {
      sys.props.get("spark.ui.proxyBase")
        .orElse(sys.env.get("APPLICATION_WEB_PROXY_BASE"))
        .orElse(knoxBasePath)
        .getOrElse("")
    }
  }

```
